### ISSUE TITLE
[Request] MySQL Support

### ISSUE THREAD

**Issue by Sejadis** [Cliffield/pogo_heatmaps#1]
nice work!

but could you add support for mysql databases? would be very nice too :)

**Comment by Cliffield** [comment]
I  like to. But up to now my running PokemonGo-Maps Server don't want to communicate with my MariaDB-Server (Error: Specified key was too long; max key length is 767 bytes). I am still investigating.

**Comment by afairgiant** [comment]
+1

Also great work on this! I've been looking for something like this! 

Check out [#2262](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2262)

**Comment by MrDibbley** [comment]
this works for my MariaDB on Centos? obviously change the db user password to yours....

```
`import os
from jinja2 import Environment, FileSystemLoader
#import sqlite3
import MySQLdb
import pandas as pd

# define output folder
output_folder = "/usr/share/nginx/html/maps"

# define database
#database = "/tmp/PokemonGo-Map/pogom.db"

db = MySQLdb.connect(
            db="PokemonGo",
            user="PokemonGo",
            passwd="PokemonGo",
            host="localhost")

# connect to database
#con = sqlite3.connect(database)

# get table pokemon
df = pd.read_sql_query("SELECT * from pokemon", db)

# close connection to database
#con.close()
db.close;
`
```

**Comment by Cliffield** [comment]
MySQL support added
