### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 81: ordinal not in range(128)

### ISSUE THREAD

**Issue by hagehg** [Cliffield/pogo_heatmaps#3]
Hi, trying to run this I get the following error:

`$ python createheatmaps.py`
`Traceback (most recent call last):`
`File "createheatmaps.py", line 124, in <module>`
`main()`
`File "createheatmaps.py", line 59, in main`
`create_maps_html()`
`File "createheatmaps.py", line 56, in create_maps_html`
`f.write(html)`
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 81: ordinal not in range(128)`

Any idea what I am doing wrong?

Thanks!

**Comment by hagehg** [comment]
Got it to work now.

Instead of copying the heatmap script to the pokemongo-map folder, I copied the pogom.db file into the heatmap folder and then it worked

**Comment by Cliffield** [comment]
Hi, due to encoding problems with male and female symbols in the pokemon names i replaced them in the provided pokemon.*.json files with (m) and (f). It's more a workaround till i solve the underlying problem.
Thanks for your feedback.
