### ISSUE TITLE
Can't encode character, using fr language

### ISSUE THREAD

**Issue by Plop** [Cliffield/pogo_heatmaps#4]
Hi,

When running the script with language = fr, I got this error.

```
root@pokemaps:/var/www/heatmap# python createheatmaps.py
Traceback (most recent call last):
  File "createheatmaps.py", line 127, in <module>
    create_index()
  File "createheatmaps.py", line 72, in create_index
    f.write(html)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 3083: ordinal not in range(128)
```

How can I fix this ? Thanks.

**Comment by Cliffield** [comment]
I fixed the encoding error... hopefully.
Get update.

**Comment by Plop** [comment]
Same issue :/
And there is a missing )
f.write(html.encode("UTF-8") >>> f.write(html.encode("UTF-8"))

**Comment by Cliffield** [comment]
Cant reproduce the error on my setup (windows and linux with python2.7) since the encode("UTF-8") insertion. But I'll keep trying to solve this nagging issue.

**Comment by Plop** [comment]
Well, I completely deleted the directory and done a git clone again. Seems like it's working now. Thanks ! :)
